//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoAnVienSinhHoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VSHEntities1 : DbContext
    {
        public VSHEntities1()
            : base("name=VSHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KhachHangTaiKhoan> KhachHangTaiKhoans { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<DoiTac> DoiTacs { get; set; }

        internal int spDuyetSP(int id, int maChung)
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<DuAn> DuAns { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<Huyen> Huyens { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Tinh> Tinhs { get; set; }
        public virtual DbSet<Xa> Xas { get; set; }
        public virtual DbSet<KhachHangTaiKhoan1> KhachHangTaiKhoan1 { get; set; }
        public virtual DbSet<viewHoSoKH> viewHoSoKHs { get; set; }
        public virtual DbSet<viewSqlLogin> viewSqlLogins { get; set; }
        public virtual DbSet<viewThongTinNhanVien> viewThongTinNhanViens { get; set; }
    
        public virtual int spDangKy1(string tenTaiKhoan, string matKhau, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, Nullable<int> maXa)
        {
            var tenTaiKhoanParameter = tenTaiKhoan != null ?
                new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
                new ObjectParameter("tenTaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var maXaParameter = maXa.HasValue ?
                new ObjectParameter("maXa", maXa) :
                new ObjectParameter("maXa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDangKy1", tenTaiKhoanParameter, matKhauParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, maXaParameter);
        }
    
        public virtual ObjectResult<spSearch_SanPham_Result> spSearch_SanPham(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSearch_SanPham_Result>("spSearch_SanPham", strSearchParameter);
        }
    
        public virtual ObjectResult<spShowViewKHTK_Result> spShowViewKHTK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spShowViewKHTK_Result>("spShowViewKHTK");
        }
    
        public virtual ObjectResult<spHuyenTheoTinh_Result> spHuyenTheoTinh(Nullable<int> maTinh)
        {
            var maTinhParameter = maTinh.HasValue ?
                new ObjectParameter("maTinh", maTinh) :
                new ObjectParameter("maTinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spHuyenTheoTinh_Result>("spHuyenTheoTinh", maTinhParameter);
        }
    
        public virtual ObjectResult<spXaTheoHuyen_Result> spXaTheoHuyen(Nullable<int> maHuyen)
        {
            var maHuyenParameter = maHuyen.HasValue ?
                new ObjectParameter("maHuyen", maHuyen) :
                new ObjectParameter("maHuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spXaTheoHuyen_Result>("spXaTheoHuyen", maHuyenParameter);
        }
    
        public virtual int spCapNhatMatKhau(string tenTK, string matKhauMoi)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("tenTK", tenTK) :
                new ObjectParameter("tenTK", typeof(string));
    
            var matKhauMoiParameter = matKhauMoi != null ?
                new ObjectParameter("matKhauMoi", matKhauMoi) :
                new ObjectParameter("matKhauMoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCapNhatMatKhau", tenTKParameter, matKhauMoiParameter);
        }
    
        public virtual ObjectResult<spShowHoSoKH_Result> spShowHoSoKH(string tenTaiKhoan)
        {
            var tenTaiKhoanParameter = tenTaiKhoan != null ?
                new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
                new ObjectParameter("tenTaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spShowHoSoKH_Result>("spShowHoSoKH", tenTaiKhoanParameter);
        }
    
        public virtual ObjectResult<spSanPhamDaDat_Result> spSanPhamDaDat(string tenTaiKhoan)
        {
            var tenTaiKhoanParameter = tenTaiKhoan != null ?
                new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
                new ObjectParameter("tenTaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSanPhamDaDat_Result>("spSanPhamDaDat", tenTaiKhoanParameter);
        }
    
        public virtual ObjectResult<spTimSPKhongMa_Result> spTimSPKhongMa(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTimSPKhongMa_Result>("spTimSPKhongMa", strSearchParameter);
        }
    
        public virtual ObjectResult<string> spKiemTraThongTinDangNhap(string name, string password)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spKiemTraThongTinDangNhap", nameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<spKiemTraThongTinDangNhap1_Result> spKiemTraThongTinDangNhap1(string name, string password)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spKiemTraThongTinDangNhap1_Result>("spKiemTraThongTinDangNhap1", nameParameter, passwordParameter);
        }
    
        public virtual int spThemNhanVien(string tenTaiKhoan, string matKhau, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, Nullable<decimal> luong, string sdt, string email, Nullable<int> maCV, Nullable<int> maPB, Nullable<int> maXa, string diaChi)
        {
            var tenTaiKhoanParameter = tenTaiKhoan != null ?
                new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
                new ObjectParameter("tenTaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("maPB", maPB) :
                new ObjectParameter("maPB", typeof(int));
    
            var maXaParameter = maXa.HasValue ?
                new ObjectParameter("maXa", maXa) :
                new ObjectParameter("maXa", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemNhanVien", tenTaiKhoanParameter, matKhauParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, luongParameter, sdtParameter, emailParameter, maCVParameter, maPBParameter, maXaParameter, diaChiParameter);
        }
    
        public virtual int spDuyetDon(Nullable<int> maNV, Nullable<int> maHD)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(int));
    
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDuyetDon", maNVParameter, maHDParameter);
        }
    
        public virtual int spDuyetSP(Nullable<int> maSP, string maCH)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(int));
    
            var maCHParameter = maCH != null ?
                new ObjectParameter("maCH", maCH) :
                new ObjectParameter("maCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDuyetSP", maSPParameter, maCHParameter);
        }
    }
}
