//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoAnVienSinhHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            HinhAnh = "~/Content/images/test.png";
        }

        public int ID { get; set; }
        public string MaChung { get; set; }
        public string TenKhoaHoc { get; set; }
        public string DongDanh { get; set; }
        public string TenBanDau { get; set; }
        public string TenThuongGoi { get; set; }
        public string KichThuoc { get; set; }
        public string ToChucCoThe { get; set; }
        public string NguoiPhanLap { get; set; }
        public string NamPhanLap { get; set; }
        public string NguoiDinhDanh { get; set; }
        public Nullable<System.DateTime> NgayKiGuiMau { get; set; }
        public string ViTriThuMau { get; set; }
        public string ChauLuc { get; set; }
        public string QuocGia { get; set; }
        public string MoiTruongThuMau { get; set; }
        public string DieuKienNuoiCoBan { get; set; }
        public string SanSinhDocTo { get; set; }
        public string TinhTrangCuaChung { get; set; }
        public string SuChongLaiKhuayDong { get; set; }
        public string ThongTinGen { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaLop { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual Lop Lop { get; set; }
        [NotMapped]
        public HttpPostedFileBase imgUpload { get; set; }
    }
}